[package]
name = "flamboyant"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
libc = "^0.2"
rb-sys = { version = "^0.9", features = ["link-ruby"] }
coffret = "0.0.3"
ctrlc = "3.2.2"
nix = "0.24.1"
